version: 2

sources:
  - name: raw
    database: market-data-pipeline-490602
    schema: marketdatapipeline
    tables:
      - name: daily_bars
      - name: splits
      - name: tickers

models:
  - name: stg_daily_bars
    columns:
      - name: symbol
        tests:
          - not_null
      - name: t
        tests:
          - not_null
      - name: c
        tests:
          - not_null
      - name: v
        tests:
          - not_null