select
    ticker,
    cast(fiscal_period as string) as fiscal_period,
    cast(fiscal_year as string) as fiscal_year,
    cast(start_date as date) as period_start,
    cast(end_date as date) as period_end,
    coalesce(cast(filing_date as date), cast(end_date as date)) as filing_date,
    cast(revenues as float64) as revenues,
    cast(cost_of_revenue as float64) as cost_of_revenue,
    cast(gross_profit as float64) as gross_profit,
    cast(operating_income_loss as float64) as operating_income,
    cast(net_income_loss as float64) as net_income,
    cast(basic_earnings_per_share as float64) as basic_eps,
    cast(diluted_earnings_per_share as float64) as diluted_eps,
    cast(assets as float64) as total_assets,
    cast(current_assets as float64) as current_assets,
    cast(noncurrent_assets as float64) as noncurrent_assets,
    cast(liabilities as float64) as total_liabilities,
    cast(current_liabilities as float64) as current_liabilities,
    cast(equity as float64) as total_equity,
    cast(net_cash_flow_from_operating_activities as float64) as operating_cash_flow,
    cast(net_cash_flow_from_investing_activities as float64) as investing_cash_flow,
    cast(net_cash_flow_from_financing_activities as float64) as financing_cash_flow
from {{ source('raw', 'quarterly_financials') }}
