version: 2

models:

  - name: mart_daily_returns
    columns:
      - name: composite_figi
        tests:
          - not_null
      - name: ticker
        tests:
          - not_null
      - name: price_date
        tests:
          - not_null

  - name: fact_daily_prices
    columns:
      - name: composite_figi
        tests:
          - not_null
      - name: ticker
        tests:
          - not_null
      - name: price_date
        tests:
          - not_null
      - name: close_price
        tests:
          - not_null
      - name: volume
        tests:
          - not_null